[build]
  command = "pnpm build"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-sitemap"

  [plugins.inputs]
    buildDir = "public"
